apiVersion: v1
kind: Service
metadata:
  name: minikubeservice
spec:
  type: NodePort
  selector:
    app: minikubeapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31500
